sudo: false
dist: trusty
language: java
jdk:
  - oraclejdk8
#  - oraclejdk9
#  - oraclejdk11
script: mvn cobertura:cobertura -DskipTests=false

services:
  - mysql
  - redis

#git:
#  depth: 3
#branches:
#  only:
#    - master

before_script:
  - mysql -e "CREATE DATABASE rebuild10 DEFAULT CHARSET utf8 COLLATE utf8_general_ci;"
  - mysql -e "CREATE USER 'rebuild'@'127.0.0.1' IDENTIFIED BY 'rebuild'; GRANT ALL PRIVILEGES ON rebuild10.* TO 'rebuild'@'127.0.0.1'; FLUSH PRIVILEGES;"
  - mysql -D rebuild10 < .setup/db-init.sql

# codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
